kind: Cluster
apiVersion: kind.x-k8s.io/vlalpha4
nodes:
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080