#deployment app rotten-potates com persistencia no mongodb
#Deployment MongoDB
apiVersion: apps/v1 #confirmar com kubectl api-resources
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
    template:
      metadata:
        labels:
          app: mongodb #tem que casar com o que foi passado no matchLabels
      spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valeu: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valeu: mongopwd

---

#Service do Mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      protocol: TCP
  type: ClusterIP

---

#Deployment do app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
    template:
      metadata:
        labels:
          app: web
      spec:
      containers:
        - name: web
          image: alexandrebunn/rotten-potatoes:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              valeu: "admin"
            - name: MONGODB_HOST
              valeu: "mongodb"
            - name: MONGODB_PORT
              valeu: "27017"
            - name: MONGODB_USERNAME
              valeu: "mongouser"
            - name: MONGODB_PASSWORD
              valeu: "mongopwd"
---

#Service do APP Web
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 5000
      NodePort: 30000
      protocol: TCP
  type: NodePort