
name: CI+CD

on:
  push:
    branches: [ conf-kubernetes ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:    
          username: ${{ secrets.DOCKERHUB_USER }}
          password:  ${{ secrets.DOCKERHUB_PWD }}
