
name: CI+CD

on:
  push:
    branches: [ conf-kubernetes ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:    
          username: ${{ secrets.DOCKERHUB_USER }}
          password:  ${{ secrets.DOCKERHUB_PWD }}

      - name: Docker build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: 
            763ed2a0a734/rotten-potatoes:latest
