# This is a basic workflow to help you get started with Actions

name: CI-CD # Nome do workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ meubranch ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    # Agente de execucao ... setup de maquina que eu preciso executar meu pipeline
    runs-on: ubuntu-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: # Execucoes que eu vou ter no job --- acoes
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 # Download do codigo no repositorio
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            jmscatena/rotten-potatoes:latest
            jmscatena/rotten-potatoes:${{ github.run_number }}
  CD:    
    needs: CI
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 # Download do codigo no repositorio
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBCONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          images: jmscatena/rotten-potatoes:${{ github.run_number }}
          manifests: |
            k8s/manifest.yaml
            
      
